name: Revise Version
on:
  workflow_dispatch:
    inputs:
      clusterName:
        description: 'Cluster Name'     
        required: true
      serviceName:
        description: 'Service Name'     
        required: true  
        
jobs:
  rollback-version:
    runs-on: ubuntu-latest

    steps:
     - name: Configure AWS credentials
       uses: aws-actions/configure-aws-credentials@v1
       with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        
     - name: Login to Amazon ECR
       id: login-ecr
       uses: aws-actions/amazon-ecr-login@v1   
     
     - name: Checkout 
       uses: actions/checkout@v2
     
     - name: Run single script
       run: "bash scripts/aws_rollback.sh ${{ github.event.inputs.clusterName }} ${{ github.event.inputs.serviceName }}"
