name: Revise Version
on:
  workflow_dispatch:
    inputs:
#       clusterName:
#         description: 'Cluster Name'     
#         required: true
#       serviceName:
#         description: 'Service Name'     
#         required: true
      clusterName: 
        type: choice
        description: Choose a cluster
        options:
        - AutoRollbackTestCluster
        - Bryntum-pdf-export-server
        required: true
     
      typeName:  
        type: choice
        description: Choose one
        options:
        - stage
        - prod
        required: true

      stageName:
        type: choice
        description: Choose a stage service
        options:
        - all
        - Nginx-Web-Service
      
      prodName:
        type: choice
        description: Choose a prod service
        options:
        - all
        - SecondService
        - ThirdService
        - ${{ github.event.inputs.typeName }}
        
      
jobs:
  rollback-version:
    runs-on: ubuntu-latest

    steps:
     - name: Configure AWS credentials
       uses: aws-actions/configure-aws-credentials@v1
       with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_STAGE }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_STAGE }}
        aws-region: us-east-1
        
     - name: Login to Amazon ECR
       id: login-ecr
       uses: aws-actions/amazon-ecr-login@v1   
     
     - name: Action to check out Repo 
       uses: actions/checkout@v2
     
     - name: Run single script
       run: "bash aws_test.sh ${{ github.event.inputs.clusterName }} ${{ github.event.inputs.serviceName }}"
