name: Revise Version
on:
  workflow_dispatch:
    inputs:
      clusterName:
        type: choice
        description: Choose a cluster
        options:
          - AutoRollbackTestCluster
        required: true

      typeName:
        type: choice
        description: Choose one
        options:
          - stage
          - prod
        required: true
      
      functionName:
        type: choice
        description: Choose one
        options:
          - rollback
          - restart

      serviceName:
        type: choice
        description: Choose a service
        options:
          - all
          - Nginx-Web-Service
          - Ngix-Second
          - SecondService
          - ThirdService
        required: true  

jobs:
  stage:
    if: ${{ github.event.inputs.typeName == 'stage' }}
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_STAGE }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_STAGE }}
          aws-region: us-east-1

      - name: Action to check out Repo
        uses: actions/checkout@v2
        
        if: ${{ github.event.inputs.functionName == 'rollback' }}
      - name: Run all service
        if: ${{ github.event.inputs.serviceName == 'all' }}
        run: |
          bash aws_test.sh revert ${{ github.event.inputs.clusterName }} Nginx-Web-Service
          bash aws_test.sh revert ${{ github.event.inputs.clusterName }} Ngix-Second
      - name: Run selected service
        if: ${{ (github.event.inputs.serviceName == 'Nginx-Web-Service') || (github.event.inputs.serviceName == 'Ngix-Second') }}
        run: "bash aws_test.sh revert ${{ github.event.inputs.clusterName }} ${{ github.event.inputs.serviceName }}"

  prod:
    if: ${{ github.event.inputs.typeName == 'prod' }}
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_STAGE }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_STAGE }}
          aws-region: us-east-1

      - name: Action to check out Repo
        uses: actions/checkout@v2

      - name: Run all service
        if: ${{ github.event.inputs.serviceName == 'all' }}
        run: |
          bash aws_test.sh revert ${{ github.event.inputs.clusterName }} SecondService
          bash aws_test.sh revert ${{ github.event.inputs.clusterName }} ThirdService

      - name: Run selected service
        if: ${{ (github.event.inputs.serviceName == 'SecondService') || (github.event.inputs.serviceName == 'ThirdService') }}
        run: "bash aws_test.sh revert ${{ github.event.inputs.clusterName }} ${{ github.event.inputs.serviceName }}"


