# This is a basic workflow that is manually triggered

name: Revise Version

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      clusterName:
        description: 'Cluster Name'     
        required: true
      serviceName:
        description: 'Service Name'     
        required: true  
        
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  rollback-version:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
      - uses: actions/checkout@v2
      - run: chmod +x ./aws_test.sh
      - run: sh ./aws_test.sh ${{ github.event.inputs.clusterName }} ${{ github.event.inputs.serviceName }}
